### ISSUE TITLE
How can I use whenYouCallAction() with custom controllers namespace?

### ISSUE THREAD

**Issue by dbrw** [imanghafoori1/laravel-heyman#101]
Dear @imanghafoori1, I am very attracted to use this package on my new project. But have a question since I use Dingo/Api package with this.

I want do something like bellow:
```php
HeyMan::
whenYouCallAction('App\Api\V1\Controllers\SomeController@action')
...
```

I saw this line where you hard code the controllers' namespace https://github.com/imanghafoori1/laravel-heyman/blob/e9b436e5d2963655c6d2597df9c990d327478d0c/src/WatchingStrategies/Routes/RouteNormalizer.php#L19 my question is; how can I use my own namespace on `whenYouCallAction` function?

**Comment by imanghafoori1** [comment]
try it like this :

```php
HeyMan::whenYouCallAction('\App\Api\V1\Controllers\SomeController@action')
```
the namespace should begin with a back slash ( see before the App)

it first checks to see if there is a backslash it the beginning...

**Comment by dbrw** [comment]
Thank you for the reply. I can't make it to work, here is my setup:

## app/Providers/AuthServiceProvider.php
```php
use Imanghafoory\HeyMan\Facades\Heyman;
...
    public function boot()
    {
        HeyMan::whenYouCallAction('\App\Api\V1\Controllers\SomeController@action')
            ->always()
            ->weDenyAccess();
...
```

## app/Api/V1/Controllers/SomeController.php
```php
...
namespace App\Api\V1\Controllers;
...
class SomeController extends Controller
{
    public function action()
    {
        dd('reached');
    }
...
```

When I try to reach the action through the url, I got "reached" output, which I suppose to expect `AuthorizationException` thrown. Would you mind to give some enlightenment?

**Comment by imanghafoori1** [comment]
Let me check it
Maybe it's a subtle bug. 

But anyway I recommemd name your routes and use your route names 
Since checking action names is not a very good practice
In case you need to move your class or rename a controller method

**Comment by dbrw** [comment]
Initially I was planning to use route name since it's easier for me, but since `RouteServiceProvider` loaded after `AuthServiceProvider` I can't get the route name.

Do you ever have change the framework providers order and got any issue?
I search about framework service providers order but got no luck, maybe it's my google-fu that sucks.

**Comment by imanghafoori1** [comment]
I thnik it does not matter, you can apply heyman rules on the route names from your AuthServiceProviders.

which version of Heyman you have installed ? is it the latest?

**Comment by dbrw** [comment]
Yes, It's the latest version.

I think I will go with creating HeyManServiceProvider and declare all my HeyMan rules there.
Hopefully you're able to check the subtle bug.

Thank you!

**Comment by imanghafoori1** [comment]
sorry is your version 2.2.22 ? or above ?

you can run `composer show` to see the installed version of laravel-heyman

**Comment by dbrw** [comment]
I got `v2.2.26` from `composer show`.

**Comment by imanghafoori1** [comment]
there are a couple of bugs here. wait for me to fix them please

**Comment by imanghafoori1** [comment]
could you please change the RouteNormalizer.php class in the vendor folder to see if your problem goes away or not ?
```
    public function normalizeAction($actions): array
    {
        $addNamespace = function ($action) {
            if (\Illuminate\Support\Str::startsWith($action, '\\')) {
                return $action;
            }

            return app()->getNamespace().'Http\\Controllers\\'.$action;
        };

        return array_map($addNamespace, $actions);
    }
```

**Comment by imanghafoori1** [comment]
try the version v2.2.27

**Comment by imanghafoori1** [comment]
Try the final version since it contains important fixes
2.2.28 or above
