### ISSUE TITLE
HeyMan and Laravel policy

### ISSUE THREAD

**Issue by anurat** [imanghafoori1/laravel-heyman#122]
Is there a way to use HeyMan together with Laravel policy?  
I only found an example for Gate but no policy anywhere.

Thanks in advance.

**Comment by imanghafoori1** [comment]
I think this package eliminates the need for gates and policies altogether.
Although it can work with gates, in fact, there is no real need for that.

**Comment by imanghafoori1** [comment]
ok, suggestions are welcome. what you expect to write and it works?

**Comment by anurat** [comment]
Thank you for considering.  
Just the same thing as Gate I guess.  
Something along the line `->thisPolicyShouldAllow('PolicyClass@method')`

**Comment by imanghafoori1** [comment]
Have you tried the `->thisMethodShouldAllow('...@...')`

**Comment by anurat** [comment]
Policy method automatically injects $user to the method, for example
```php
    /**
     * Determine whether the user can view any models.
     *
     * @param  \App\Models\User  $user
     * @return mixed
     */
    public function viewAny(User $user)
    {
    }
```

When I call `->thisMethodShouldAllow('policy@method')`
the $user object is not present.  
I also couldn't retrieve user object inside AuthServiceProvider (in order to pass it as parameter).  
So I couldn't work out calling policy with thisMethodShouldAllow so far.

**Comment by imanghafoori1** [comment]
currently, you can add it in your own project. Using:
```
Heyman::defineCondition(...);
```
you can define as many condition or situation as you want.
For good examples see the source code in the plugins directory of laravel heyman package.
;)
