### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by anurat** [imanghafoori1/laravel-heyman#132]
This problem happened to me several times in the past but I did not report it thinking it could be several things.
But after encountering this problems several times during installing laravel-heyman, I try to reproduce the error.

After installing new laravel project with "laravel new name"
then run "composer require imanghafoori/laravel-heyman"
I got the following error.

```
composer require imanghafoori/laravel-heyman
Using version ^2.2 for imanghafoori/laravel-heyman
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

```

Environment: Windows 10, PHP 7.4, composer 1.10, laravel installer 4.0

**Comment by imanghafoori1** [comment]
Hi
This is not due to the package, rather it is the composer 1.* issue
You can increase the max memory of php.ini
Or you can define the exact version of packages you wanna install in composer.json to decrease memory usage. 
1.* ---> 1.3.45

**Comment by anurat** [comment]
The error said memory 1.6 GB exhausted. Why would it need that much memory and what's max memory I should set?

**Comment by imanghafoori1** [comment]
This is composer issue. Event 2.5G may get exhausted.
There nothing for me to change. You have to modify your composer.json or use composer 2.x

**Comment by anurat** [comment]
Thanks, I can install with composer 2 without errors.
