### ISSUE TITLE
laravel 10 compatibility issue

### ISSUE THREAD

**Issue by Mohsen-Nejati** [imanghafoori1/laravel-heyman#140]
Error on require in laravel v10

Using version ^2.2 for imanghafoori/laravel-heyman
./composer.json has been updated
Running composer update imanghafoori/laravel-heyman
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - imanghafoori/laravel-heyman[2.2.0, ..., 2.2.7] require laravel/framework ~5.3 -> found laravel/framework[v5.3.0, ..., v5.8.38] but it conflicts with your root composer.json require (^10.0).
    - imanghafoori/laravel-heyman[2.2.8, ..., v2.2.34] require laravel/framework ~5.1 -> found laravel/framework[v5.1.0, ..., v5.8.38] but it conflicts with your root composer.json require (^10.0).
    - imanghafoori/laravel-heyman[v2.2.35, ..., v2.2.43] require laravel/framework ~5.1|6.* -> found laravel/framework[v5.1.0, ..., v5.8.38, v6.0.0, ..., v6.20.44] but it conflicts with your root composer.json require (^10.0).
    - imanghafoori/laravel-heyman[v2.2.44, ..., v2.2.45] require laravel/framework ~5.1|6.*|7.* -> found laravel/framework[v5.1.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but it conflicts with your root composer.json require (^10.0).
    - imanghafoori/laravel-heyman[v2.2.46, ..., v2.2.52] require laravel/framework ~5.1|6.*|7.*|8.* -> found laravel/framework[v5.1.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.0).
    - imanghafoori/laravel-heyman[v2.2.53, ..., v2.2.54] require laravel/framework ~5.1|6.*|7.*|8.*|9.* -> found laravel/framework[v5.1.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but it conflicts with your root composer.json require (^10.0).
    - Root composer.json requires imanghafoori/laravel-heyman ^2.2 -> satisfiable by imanghafoori/laravel-heyman[2.2.0, ..., v2.2.54].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require imanghafoori/laravel-heyman:*" to figure out if any version is installable, or "composer require imanghafoori/laravel-heyman:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by imanghafoori1** [comment]
You can try the latest version. v2.2.55
