### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by Blair2004** [imanghafoori1/laravel-heyman#16]
Hi, i'm really in love with what you did and the fact that, it doesn't necessarily need to be added to an existing code (Controller) makes it more flexible. 

However, i have an issue with the spell termination. If you say "whenDoingThis", this assume the action has already taken place, and some might not understand that "whenDoingThis" is occuring before. 

So i would like to suggest renaming "when.." to "before...". This can increase the possibility because it will be possible to do something like "afterDoingThis". 

Anyway, good job. I might use it on my upcoming projects.

**Comment by imanghafoori1** [comment]
I am happy to see that a lot of people like the idea right after it is released.
I consider what mentioned for the next major release.
Do not hesitate if you had other ideas as well.

**Comment by fgilio** [comment]
I like this suggestion 👍 

Awesome package @imanghafoori1  👏

**Comment by imanghafoori1** [comment]
I appreciate if you help me spreading the word and introduce it to other people.

**Comment by fgilio** [comment]
I'm already on it :smile:

**Comment by imanghafoori1** [comment]
I reopen the issue so others can write their opinion.

**Comment by adelinferaru** [comment]
HeyMan::beforeReadCommentFrom('github_user', 'adelinferaru')->expect('instance', 'CongratulationsInterface')->otherwise()->expect('instance', 'SuggestionInterface');

Nice job. Keep improving.

**Comment by imanghafoori1** [comment]
@adelinferaru
```php
 HeyMan::thankYou();
```
I would be happy if you help me spread the word by sharing the link in laravel social groups .
So I can spend more time on coding.
