### ISSUE TITLE
Some grouped suggestions

### ISSUE THREAD

**Issue by Blair2004** [imanghafoori1/laravel-heyman#17]
### New Method : `AssertThat( boolean )`

As what i can see, the library is closely linked to plain Laravel installation. However, many out there already have a laravel application with their superset of functions (classes). So, we might introduce an asset true (or assertThat) method, which give the developper the capacity to to his own assetion and proceed (or not) the even. 

Example : 

```php
use App\Factory\Post as PostFactory;
// ...
HeyMan::whenYouDelete( App\Models\Post::class )
->assertThat( PostFactory::OnePostLeft() )
// ...
```

### New Method : `redirectTo() `
Having to write down ->redirect()->to()... makes the chain more longer. We might implement a method like ->redirectTo() which join both methods.

### New Method : otherwiseThrow( \Exception )
Well, we're handling exception in a different ways on our laravel application. I assume many might have a different view (message) for different exceptions. It might be interesting on the chain to throw an exception. 
Edit : i've seen that there is a Exception method, we might then consider reducing the chain.

Example : 

```php
use App\Guards\HeavenGuard;
use Illuminate\Support\Auth;
use App\Exceptions\NotForYouException;
// ...
HeyMan::whenYouVisitUrl(  '/paradise'  )
->assertThat( HeavenGuard::isBlessed( Auth::user() ) ) // new method
->otherwiseThrow( NotForYouException::class )
// ...
```

### New method : `whenYouVisiteRoute()`
instead of typing down the URL with slashes, we might have a route support method.

**Comment by Blair2004** [comment]
2 - what about if the controller we would like to redirect to use $_GET properties ? And what about we're using flash data. I think (i might be wrong) that `redirectTo(string,array of flash data)` might be more suitable for that use case.
3 - Okay... however having long chain might make it more difficult to read. Assume a long HeyMan:: scripts... we'll have repetitive `otherwise()`. I'm not point that it's not useful, but we can directly link that to known method like : 
`
otherwiseRedirectTo()
otherwiseThrowNew()
otherwiseFireEvent()
otherwiseAbord()
otherwiseResponse()
otherwiseDeny()
`
That might be good for the feature. it's just an idea.

**Comment by imanghafoori1** [comment]
You can chain `with` and other methods which are available on the laravel `redirect()` helper function.

**Comment by imanghafoori1** [comment]
There are many technical issues with merging the otherwise method with the proceeding methods.

**Comment by Blair2004** [comment]
okay then. Thank you again for your time.
